site_name: OODEEL

# Set navigation here
nav:
  - Home: index.md
  - Tutorials:
    - "Getting started: Maximum Logit Score on MNIST": pages/demo_experiment.ipynb
    - Important Note On Feature Extractors: pages/feature_extractor_tuto.ipynb
    - OOD Baselines (Tensorflow):
      - ODIN: notebooks/tensorflow/demo_odin_tf.ipynb
      - DKNN: notebooks/tensorflow/demo_dknn_tf.ipynb
      - VIM: notebooks/tensorflow/demo_vim_tf.ipynb
      - Energy: notebooks/tensorflow/demo_energy_tf.ipynb
      - Mahalanobis: notebooks/tensorflow/demo_mahalanobis_tf.ipynb
    - OOD Baselines (Torch):
      - ODIN: notebooks/torch/demo_odin_torch.ipynb
      - DKNN: notebooks/torch/demo_dknn_torch.ipynb
      - VIM: notebooks/torch/demo_vim_torch.ipynb
      - Energy: notebooks/torch/demo_energy_torch.ipynb
      - Mahalanobis: notebooks/torch/demo_mahalanobis_torch.ipynb
    - Advanced Topics:
      - Seamlessly handling torch and tf datasets with DataHandler: pages/datahandler_tuto.md
      - Seamlessly handling torch and tf Tensors with Operator: pages/operator_tuto.md
      - Implementing your own baseline: pages/implementing_baselines_tuto.ipynb
  - API Reference:
    - OOD methods: api/methods.md
    - Metrics: api/metrics.md
    - OOD dataset: api/ooddataset.md
    - DataHandlers:
      - TFDataHandler: api/tf_datahandler.md
      - TorchDataHandler: api/torch_datahandler.md
    - Operators:
      - TorchOperator: api/torch_operator.md
      - TFOperator: api/tf_operator.md
    - FeatureExtractors:
      - KerasFeatureExtractor: api/keras_feature_extractor.md
      - TorchFeatureExtractor: api/torch_feature_extractor.md
    - Training tools: api/training_funs.md
    - Utils: api/utils.md
  - Contributing: CONTRIBUTING.md

theme:
  name: "material"
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      primary: dark
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      ignore: ["ignored_notebooks/*"]
      ignore_h1_titles: True
      include_source: True

markdown_extensions:
  - footnotes
  - extra
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - codehilite
  - toc:
      baselevel: 1
      permalink: true
      toc_depth: 1-4
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/custom.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/custom.js

repo_name: "deel-ai/oodeel"
repo_url: "https://github.com/deel-ai/oodeel"
