site_name: OODEEL

# Set navigation here
nav:
  - Home: index.md
  - API Reference:
    - OOD methods: api/methods.md
    - Metrics: api/metrics.md
    - OOD dataset: api/ooddataset.md
    - DataHandlers:
      - TFDataHandler: api/tf_datahandler.md
      - TorchDataHandler: api/torch_datahandler.md
    - Operators:
      - TorchOperator: api/torch_operators.md
      - TFOperator: api/tf_operators.md
    - Training tools: api/training_funs.md
  - Tutorials:
    - Get Started: notebooks/demo_experiment.ipynb
    - Tensorflow:
      - ODIN: notebooks/demo_odin.ipynb
      - DKNN: notebooks/demo_dknn.ipynb
      - VIM: notebooks/demo_vim.ipynb
      - Energy: notebooks/demo_energy.ipynb
    - Torch:
      - ODIN: notebooks/torch/demo_odin_torch.ipynb
      - DKNN: notebooks/torch/demo_dknn_torch.ipynb
      - VIM: notebooks/torch/demo_vim_torch.ipynb
      - Energy: notebooks/torch/demo_energy_torch.ipynb
  - Contributing: CONTRIBUTING.md

theme:
  name: "material"
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      primary: dark
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      ignore: ["ignored_notebooks/*"]

markdown_extensions:
  - footnotes
  - extra
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - codehilite
  - toc:
      baselevel: 1
      permalink: true
      toc_depth: 1-4
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/custom.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/custom.js

repo_name: "deel-ai/oodeel"
repo_url: "https://github.com/deel-ai/oodeel"
