name: oodeel tests

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 2 * * 0" # Run tests every Sunday at 2am

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        include:
          - python-version: 3.7
            tf-version: 2.4
          - python-version: 3.9
            tf-version: 2.8
          - python-version: "3.10"
            tf-version: latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test with tox (Python ${{ matrix.python-version }} - TensorFlow ${{ matrix.tf-version }})
      run: tox -e py$(echo ${{ matrix.python-version }}-tf${{ matrix.tf-version }} | tr -d .)
